Portal/Controllers/PackageController.cs
using Core.Domain.Entities;
using Core.Domain.Enumerations;
using Core.DomainServices.IServices;
using Core.DomainServices.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portal.Models;

namespace Portal.Controllers
{
    public class PackageController : Controller
    {
        private readonly IPackageService _packageService;
        private readonly IProductService _productService;
        private readonly IEmployeeService _employeeService;
        private readonly ICanteenService _canteenService;
        private readonly IStudentService _studentService;

        public PackageController(
            IPackageService packageService,
            IProductService productService,
            IEmployeeService employeeService,
            ICanteenService canteenService,
            IStudentService studentService)
        {
            _packageService = packageService;
            _productService = productService;
            _employeeService = employeeService;
            _canteenService = canteenService;
            _studentService = studentService;
        }

        // ------------------------------------------------ viewing packages ----------------------------------------------------

        [Authorize]
        public IActionResult PackageDetails(int id)
        {
            try
            {
                var package = _packageService.GetPackageById(id);

                if (package != null && package.Canteen != null)
                {
                    var cityEnum = _canteenService.GetCityEnum(package.Canteen.Value);

                    if (cityEnum == null)
                    {
                        return NotFound();
                    }

                    var model = new PackageDetailModel
                    {
                        Id = package.Id,
                        Name = package.Name,
                        PickUpDate = package.PickUp,
                        ClosingTime = package.ClosingTime,
                        Price = package.Price,
                        Type = package.Type,
                        Canteen = package.Canteen.Value,
                        City = cityEnum.Value,
                        AgeRestriction = package.AgeRestriction,
                        StudentReservation = package.StudentReservation,
                        SelectedProducts = package.Products
                    };

                    if (User.HasClaim(c => c.Type == "Role" && c.Value == "Employee"))
                    {
                        model.MyCanteen = _employeeService.GetCanteenById(this.User.Identity!.Name!);
                    }
                    return View(model);
                }
                TempData["ErrorMessage"] = "Package could not be found";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;              
            }
            return RedirectToAction("AvailablePackages");
        }


        [Authorize]
        public IActionResult AvailablePackages()
        {
            try
            {
                IEnumerable<Package> packages;
                CanteenEnum canteen;
                var viewModel = new AllPackagesModel { };

                Dictionary<CanteenEnum, CityEnum?> canteenToCityMapping = CanteenCity();

                if (User.HasClaim(c => c.Type == "Role" && c.Value == "Student"))
                {
                    packages = _packageService.GetAvailablePackages();

                    viewModel = new AllPackagesModel
                    {
                        Packages = packages,
                        CanteenToCityMapping = canteenToCityMapping
                    };
                }
                else
                {
                    canteen = _employeeService.GetCanteenById(this.User.Identity!.Name!);

                    packages = _packageService.GetPackages();

                    viewModel = new AllPackagesModel
                    {
                        Packages = packages,
                        MyCanteen = canteen,
                        CanteenToCityMapping = canteenToCityMapping
                    };

                }
                return View("AvailablePackages", viewModel);
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
            }

            return RedirectToAction("Home/Index");
        }     

        // ------------------------------------------------------- my canteen packages -----------------------------------------------

        [Authorize(Policy = "Employee")]
        public IActionResult MyCanteen()
        {
            try
            {
                var employeeId = this.User.Identity?.Name;
                if (employeeId != null)
                {
                    CanteenEnum canteen = _employeeService.GetCanteenById(employeeId);

                    IEnumerable<Package> packages = _packageService.GetPackages();
                    Dictionary<CanteenEnum, CityEnum?> canteenToCityMapping = CanteenCity();

                    var viewModel = new AllPackagesModel
                    {
                        Packages = packages,
                        MyCanteen = canteen,
                        CanteenToCityMapping = canteenToCityMapping
                    };

                    return View("MyCanteen", viewModel);
                }
                else
                {
                    TempData["ErrorMessage"] = "User is not authenticated or their identity can not be found";
                }
            } 
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            return RedirectToAction("AvailablePackages");
        }

        // ------------------------------------------------------- my reservations and reserving packages -----------------------------------------------

        [Authorize(Policy = "Student")]
        public IActionResult MyReservations()
        {
            try
            {
                var studentId = this.User.Identity?.Name;
                if (studentId != null)
                {
                    Student student = _studentService.GetStudentById(studentId);
                    var packages = _packageService.GetAllReservationsFromStudent(student);

                    Dictionary<CanteenEnum, CityEnum?> canteenToCityMapping = CanteenCity();

                    var viewModel = new AllPackagesModel
                    {
                        Packages = packages,
                        CanteenToCityMapping = canteenToCityMapping
                    };
                    return View(viewModel);
                }
                else
                {
                    TempData["ErrorMessage"] = "User is not authenticated or their identity can not be found";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            return RedirectToAction("AvailablePackages");
            
        }

        [Authorize(Policy = "Student")]
        public async Task<IActionResult> ReservePackage(int id)
        {
            try 
            { 
                var studentId = this.User.Identity?.Name;
                if (studentId != null)
                {
                    var package = _packageService.GetPackageById(id);

                    Dictionary<CanteenEnum, CityEnum?> canteenToCityMapping = CanteenCity();

                    var viewModel = new AllPackagesModel
                    {
                        Packages = _packageService.GetAvailablePackages(),
                        CanteenToCityMapping = canteenToCityMapping
                    };

                    await _packageService.ReservePackageAsync(id, studentId);
                    TempData["SuccessMessage"] = "Package reserved successfully";
                    return RedirectToAction("MyReservations");
                }
                else
                {
                    TempData["ErrorMessage"] = "User is not authenticated or their identity can not be found";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Reservation failed: " + ex.Message;              
            }
            return RedirectToAction("AvailablePackages");
        }

        

        // ----------------------------------------------------- creating a package -----------------------------------------------

        [Authorize(Policy = "Employee")]
        public async Task<IActionResult> CreatePackage()
        {
            try
            {
                // get available products
                var availableProducts = _productService.GetAllProducts();
                var availableProductsList = availableProducts
                    .Select(p => new SelectListItem
                    {
                        Value = p.Id.ToString(),
                        Text = p.Name
                    })
                    .ToList();

                // get employee canteen for offersdinners
                var canteenLocation = _employeeService.GetCanteenById(this.User.Identity!.Name!);
                var myCanteen = await _canteenService.GetCanteenByLocationAsync(canteenLocation);

                var model = new PackageModel
                {
                    AvailableProducts = availableProductsList,
                    PickUpDate = DateTime.Now.Date,
                    MyCanteenOffersDinners = myCanteen!.OffersDinners
                };

                return View(model);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error has occurred: " + ex.Message;
                return RedirectToAction("AvailablePackages");
            }
        }

        [HttpPost]

Portal/Views/Shared/_Layout.cshtml
@using Portal.ExtensionMethods;

@{

    var role = this.User.GetRole();
}

<DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - TooGoodToGo</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/Portal.styles.css" asp-append-version="true" />

        <style>
            body {
                font-family: 'Verdana';
                /* font-family: Tahoma; */
            }

            h1{
                font-family: 'Verdana';
            }

            h3{
                font-family: 'Verdana';
            }

            h2{
                font-family: 'Verdana';
            }

            .text-white-custom{
                /* color: #F5F5F5; */
                color: rgba(255, 255, 255, 0.7);
            }


            .green-bg-color{
                background-color: rgba(46, 81, 64, 0.1);
            }


            .btn-outline-light-custom {
                color: #2E5140; /* Text color */
                background-color: white; /* Transparent background */
                border: 3px solid #2E5140; /* Border color */
                font-weight: 600;            }

            .btn-outline-light-custom:hover {
                color: white; /* Change text color on hover */
                background-color: #2E5140; /* Change background on hover */
                border-color: #2E5140; /* Change border color on hover */
            }


            .btn-login-custom{
                font-size: 1.4em;
                font-weight: 600;
            }

            .badge {
                font-size: 0.8em;
            }

            .icon-bg {
                background-color: #173121;
                padding: 5px; 
                border-radius: 8px; 
                display: inline-block; 
                margin-right: 10px; 
                color: white; 
                font-size: 1.2em;
            }

            .card-title {
                font-size: 1.5em; 
                font-weight: 500;
            }

            .card-text {
                font-size: 1.1em; 
            }

            .details-text {
                font-size: 1.3em;
            }

            .disclaimer-text {
                font-style: italic;
                color: #888;
                text-align: center;
                margin-top: 20px;
            }


            .scrollable-products {
                max-height: 400px; 
                overflow-y: scroll;
                overflow-x: hidden;
            }

            .container-fluid {
                padding: 0;               
            }

            .main-content {
            }

            .navbar-nav .nav-link {
                font-size: 1.4em;
                font-weight: 600;
                margin-left: 35px;
                color: white;
            }

            .page-header {

            }


            .link {
                color: #2E5140;
                display: inline-block;
                height: 50px;
            }

            .link:hover {
                    color: #0e1c15;
            }



            .link-light-custom{
                color: #FCF3E2;
                display: inline-block;
                height: 50px;
            }



            .a {
                display: block;
                width: 30px;
                height: 30px;
                position: relative;
                z-index: 1;
                padding: 10px;
            }

            .text-green {
                color: #2E5140;
            }

            .text-darkgreen{
                color: 173121;
            }

            .light-bg-color{
                background-color: #FCF3E2;
            }

            .white-bg-color{
                background-color: white;
            }

            .dgreen-bg-color {
                background-color: #2E5140;
            }

            .lgreen-bg-color {
                /* background-color: #EAF0EC; */
                /* background-color: #668576; */
                /* background-color: #E2EDD4 */
                /* background-color: #D8E8D6; */
                background-color: rgba(119, 145, 133, 0.2);
            }

            .btn-custom {
                width: 100%;
                height: 100%;
            }

            .btn-green-color {
                background-color: #2E5140;
                color: white;
            }

            .btn-green-color:hover {
                background-color: #173121;
                color: white;
            }

            .btn-dark-color {
                background-color: #173121;
                color: white;
            }

            .btn-dark-color:hover {
                background-color: #0e1c15;
                color: white;
            }


            .custom-checkbox input[type=checkbox] {
                accent-color: #2E5140;
            }

            .package-image {
                max-width: 100%;
                max-height: 100%;
                height: 250px;
                object-fit: cover;
            }

            .footer {
                position: absolute;
                bottom: 0;
                width: 100%;
                white-space: nowrap;
                line-height: 60px;
            }

            /* form pages */

            .form-group {
                margin-bottom: 20px;
            }

            label {
                font-size: 18px;
                font-weight: bold;
            }

            .checkbox-label {
                font-weight: normal;
            }

        </style>

    </head>
    <body>

        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm dgreen-bg-color">
                <div class="container-fluid px-3">
                    <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/img/TGLogo.png" alt="Logo" width="80" height="60">
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse ml-auto d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index" aria-label="Home Page">Home</a>
                            </li>
                            <li class="nav-item ml-auto">
                                <a class="nav-link" href="/#about-section" onclick="smoothScrollTo('about-section')" aria-label="About Section">About</a>
                            </li>
                            <li class="nav-item">
                                @if (role == "Student")
                                {
                                    <a class="nav-link" asp-area="" asp-controller="Package" asp-action="AvailablePackages" aria-label="Available Packages">Available Packages</a>
                                }
                                else if (role == "Employee")
                                {
                                    <a class="nav-link" asp-area="" asp-controller="Package" asp-action="AvailablePackages" aria-label="All Packages">All Packages</a>
                                }
                                else
                                {
                                    <a class="nav-link" asp-area="" asp-controller="Package" asp-action="AvailablePackages" aria-label="Packages">Packages</a>
                                }
                            </li>

                            @if (role == "Student")
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Package" asp-action="MyReservations" aria-label="My Reservations">My Reservations</a>
                                </li>
                            }

                            @if (role == "Employee")
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Package" asp-action="MyCanteen" aria-label="My Canteen">My Canteen</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Package" asp-action="CreatePackage" aria-label="Create Package">Create Package</a>
                                </li>
                            }
                        </ul>

                        <ul class="navbar-nav ml-auto">
                            @if (User.Identity!.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="btn btn-outline-light btn-login-custom px-4" asp-area="" asp-controller="Account" asp-action="Logout" aria-label="Logout"><span class=""><i class="bi bi-person-circle"></i></span> Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="btn btn-outline-light btn-login-custom px-4" asp-area="" asp-controller="Account" asp-action="Login" asp-route-returnUrl="/Home/Index" aria-label="Login"><span class=""><i class="bi bi-person-circle"></i></span> Login</a>
                                </li>
                            }
                        </ul>



                    </div>
                </div>
            </nav>
        </header>



        <div class="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="footer text-muted dgreen-bg-color py-4 mt-auto pt-3">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Avans TooGoodToGo 2023</div></div>
                    <div class="col-auto">
                        <a class=" small text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class=" small text-white" href="https://www.avans.nl/over-avans">About Avans</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class=" small text-white" href="https://www.avans.nl/over-avans/contact-en-locaties">Contact</a>
                    </div>
                </div>
            </div>
        </footer>


        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>


        <script>
            function smoothScrollTo(targetId) {
                const targetElement = document.getElementById(targetId);
                if (targetElement) {
                    window.scrollTo({
                        top: targetElement.offsetTop,
                        behavior: 'smooth'
                    });
                }
            }
        </script>

        <script>
            // Zoek het Price inputveld op basis van de asp-for attribuut
            const priceInput = document.querySelector('input[id="Price"]');

            // Voeg een eventlistener toe om het gedrag aan te passen wanneer de gebruiker het veld verlaat
            priceInput.addEventListener('blur', function () {
                // Haal de huidige waarde op
                const value = priceInput.value;

                // Vervang komma's door punten
                const formattedValue = value.replace(/,/g, '.');

                // Update de waarde in het inputveld
                priceInput.value = formattedValue;
            });
        </script>


        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>